# Generated by Django 4.0.6 on 2022-12-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreapp', '0006_alter_incidentreport_action_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='upload_photo',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
