# Generated by Django 4.0.6 on 2022-12-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreapp', '0007_incidentreport_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='upload_photo',
            field=models.ImageField(blank=True, null=True, upload_to='IncidentPhoto'),
        ),
    ]
